version: "3.8"
services:
  ocserv:
    build: .
    image: seanzhong/ocserv-docker
    restart: always
    volumes:
      - ./etc:/etc/ocserv
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    privileged: true
    # logging: #logging configuration
    #   driver: "json-file"
    #   options:
    #     max-size: "1M"
    #     max-file: "100"
    # deploy: #resource limitation
    #   resources:
    #     limits:
    #       cpus: "1"
    #       memory: "500M"
    #     reservations:
    #       memory: "50M"