#!/bin/sh

## Usage: create-user "username" "password", it will generate a password file username.password under etc/user/


username=$1
if [ -z $username ]
then
 echo "please enter in this foramat >>  create-user username password"
exit 0
fi

passwd=$(openssl rand -hex 4)
password=${2:-$passwd}

# email=$2

containerid=$(docker ps  | grep vpn_run | awk '{print $1}')

echo $password > etc/user/$username.password
echo $password |  docker exec -i $containerid ocpasswd $username

echo user has been generated with following information
echo "user: $username   
password: $password"

## TODO
# Send this to password 

## Protect the user keys
chmod -R 700 etc/